-- ============================================================
-- OPTIMIZE V4.1 — MASSIVE COLLECTION UPDATE
-- 200 cartes + 100 compagnons + codes Supabase + colonnes boutique/gacha
-- Ne supprime pas tes données utilisateur.
-- ============================================================

alter table public.companions add column if not exists price integer not null default 0;
alter table public.companions add column if not exists gacha_only boolean not null default false;
alter table public.companions add column if not exists starter boolean not null default false;
alter table public.companions add column if not exists value text;
alter table public.companions add column if not exists boost_scope text not null default 'equipped';

create table if not exists public.secret_codes (
  code text primary key,
  label text,
  message text,
  reward_type text not null default 'tickets',
  reward_id text,
  tickets integer not null default 0,
  min_level integer not null default 1,
  active boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.user_secret_codes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  code text not null,
  reward_type text,
  reward_id text,
  used_at timestamptz not null default now(),
  unique(user_id, code)
);

insert into public.reward_cards
(id, name, rarity, category, description, condition_hint, boost_type, boost_value, season, icon, active, unlocks)
values
('card_v41_common_001','Pulse YouTube','common','creative','Carte common liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',0,'permanent','🎥',true,null),
('card_v41_common_002','Cyber PWA','common','tech','Carte common liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',0,'permanent','🖥️',true,null),
('card_v41_common_003','Alpha Quête','common','gaming','Carte common liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',0,'permanent','⚡',true,null),
('card_v41_common_004','Vector Gacha','common','gaming','Carte common liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',0,'permanent','🎮',true,null),
('card_v41_common_005','Mini Objectif','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','📌',true,null),
('card_v41_common_006','Echo Ordre','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','🗓️',true,null),
('card_v41_common_007','Mini Badge','common','gaming','Carte common liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',0,'permanent','🏆',true,null),
('card_v41_common_008','Soft Budget','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','🛒',true,null),
('card_v41_common_009','Quantum HTML','common','tech','Carte common liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',0,'permanent','🟩',true,null),
('card_v41_common_010','Nexus Achat','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','🎧',true,null),
('card_v41_common_011','Origin Agenda','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','📇',true,null),
('card_v41_common_012','Hyper Agenda','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','🎧',true,null),
('card_v41_common_013','Alpha Achat','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','🎧',true,null),
('card_v41_common_014','Alpha Agenda','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','💰',true,null),
('card_v41_common_015','Alpha Mémoire','common','study','Carte common liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',0,'permanent','📖',true,null),
('card_v41_common_016','Nova Quête','common','gaming','Carte common liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',0,'permanent','⚡',true,null),
('card_v41_common_017','Beta GitHub','common','tech','Carte common liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',0,'permanent','🖥️',true,null),
('card_v41_common_018','Soft Mémoire','common','study','Carte common liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',0,'permanent','🧮',true,null),
('card_v41_common_019','Quantum Événement','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','🛒',true,null),
('card_v41_common_020','Quantum Interface','common','tech','Carte common liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',0,'permanent','🖥️',true,null),
('card_v41_common_021','Cyber Checklist','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','🗓️',true,null),
('card_v41_common_022','Origin Focus','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','🧩',true,null),
('card_v41_common_023','Beta Focus','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','🗓️',true,null),
('card_v41_common_024','Hyper Loot','common','gaming','Carte common liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',0,'permanent','🎮',true,null),
('card_v41_common_025','Hyper Dashboard','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','🎯',true,null),
('card_v41_common_026','Quantum Miniature','common','creative','Carte common liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',0,'permanent','🎥',true,null),
('card_v41_common_027','Orbit Inventaire','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','📇',true,null),
('card_v41_common_028','Neo Méthode','common','study','Carte common liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',0,'permanent','📚',true,null),
('card_v41_common_029','Nexus Cours','common','study','Carte common liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',0,'permanent','✏️',true,null),
('card_v41_common_030','Soft Checklist','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','🧩',true,null),
('card_v41_common_031','Nexus Focus','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','✅',true,null),
('card_v41_common_032','Alpha Mémoire','common','study','Carte common liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',0,'permanent','📘',true,null),
('card_v41_common_033','Origin Pixel','common','creative','Carte common liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',0,'permanent','🎨',true,null),
('card_v41_common_034','Pulse Méthode','common','study','Carte common liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',0,'permanent','🔬',true,null),
('card_v41_common_035','Beta Studio','common','creative','Carte common liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',0,'permanent','🟦',true,null),
('card_v41_common_036','Core Script','common','creative','Carte common liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',0,'permanent','💡',true,null),
('card_v41_common_037','Pixel Loot','common','gaming','Carte common liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',0,'permanent','🕹️',true,null),
('card_v41_common_038','Quantum Organisation','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','🎧',true,null),
('card_v41_common_039','Neo Couleur','common','creative','Carte common liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',0,'permanent','🎨',true,null),
('card_v41_common_040','Orbit Loot','common','gaming','Carte common liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',0,'permanent','🏆',true,null),
('card_v41_common_041','Quantum JavaScript','common','tech','Carte common liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',0,'permanent','🛠️',true,null),
('card_v41_common_042','Nexus Dessin','common','creative','Carte common liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',0,'permanent','🖌️',true,null),
('card_v41_common_043','Prime Fiche','common','study','Carte common liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',0,'permanent','📚',true,null),
('card_v41_common_044','Mini Notion','common','study','Carte common liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',0,'permanent','📘',true,null),
('card_v41_common_045','Core Cours','common','study','Carte common liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',0,'permanent','✏️',true,null),
('card_v41_common_046','Nexus HTML','common','tech','Carte common liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',0,'permanent','💻',true,null),
('card_v41_common_047','Mini Dashboard','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','📝',true,null),
('card_v41_common_048','Prime Document','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','📄',true,null),
('card_v41_common_049','Core Routine','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','🎯',true,null),
('card_v41_common_050','Spark Sac','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','💰',true,null),
('card_v41_common_051','Pulse Mission','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','🎯',true,null),
('card_v41_common_052','Beta Budget','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','🎒',true,null),
('card_v41_common_053','Pixel Semaine','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','✅',true,null),
('card_v41_common_054','Alpha Sac','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','🎧',true,null),
('card_v41_common_055','Hyper Semaine','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','✅',true,null),
('card_v41_common_056','Prime GitHub','common','tech','Carte common liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',0,'permanent','🐙',true,null),
('card_v41_common_057','Hyper Document','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','🎧',true,null),
('card_v41_common_058','Vector Agenda','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','🏠',true,null),
('card_v41_common_059','Pulse Objectif','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','🧭',true,null),
('card_v41_common_060','Prime Énergie','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','🎧',true,null),
('card_v41_common_061','Pixel Code','common','tech','Carte common liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',0,'permanent','💻',true,null),
('card_v41_common_062','Core Script','common','creative','Carte common liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',0,'permanent','🎬',true,null),
('card_v41_common_063','Spark Planning','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','🧭',true,null),
('card_v41_common_064','Vector Cours','common','study','Carte common liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',0,'permanent','🔬',true,null),
('card_v41_common_065','Orbit Objectif','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','📝',true,null),
('card_v41_common_066','Core Pixel','common','creative','Carte common liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',0,'permanent','🖌️',true,null),
('card_v41_common_067','Cyber Fiche','common','study','Carte common liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',0,'permanent','📚',true,null),
('card_v41_common_068','Cyber Pixel','common','creative','Carte common liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',0,'permanent','💡',true,null),
('card_v41_common_069','Mini Méthode','common','study','Carte common liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',0,'permanent','📚',true,null),
('card_v41_common_070','Vector Codex','common','gaming','Carte common liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',0,'permanent','🎮',true,null),
('card_v41_common_071','Pulse Ticket','common','gaming','Carte common liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',0,'permanent','🎟️',true,null),
('card_v41_common_072','Pulse Sujet','common','study','Carte common liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',0,'permanent','📖',true,null),
('card_v41_common_073','Core CSS','common','tech','Carte common liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',0,'permanent','🌐',true,null),
('card_v41_common_074','Vector Organisation','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','📄',true,null),
('card_v41_common_075','Ultra Couleur','common','creative','Carte common liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',0,'permanent','📸',true,null),
('card_v41_common_076','Pulse Planning','common','organisation','Carte common liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',0,'permanent','📌',true,null),
('card_v41_common_077','Pixel Organisation','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','📄',true,null),
('card_v41_common_078','Echo Quête','common','gaming','Carte common liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',0,'permanent','⭐',true,null),
('card_v41_common_079','Prime Contact','common','life','Carte common liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',0,'permanent','📄',true,null),
('card_v41_common_080','Ultra Script','common','creative','Carte common liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',0,'permanent','🌈',true,null),
('card_v41_rare_081','Vector Notion','rare','study','Carte rare liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',2,'permanent','🔬',true,null),
('card_v41_rare_082','Vector Notion','rare','study','Carte rare liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',2,'permanent','🧪',true,null),
('card_v41_rare_083','Nexus Supabase','rare','tech','Carte rare liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',2,'permanent','🖥️',true,null),
('card_v41_rare_084','Neo Ordre','rare','organisation','Carte rare liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',2,'permanent','📌',true,null),
('card_v41_rare_085','Vector Exercice','rare','study','Carte rare liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',2,'permanent','🧠',true,null),
('card_v41_rare_086','Mini Mission','rare','organisation','Carte rare liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',2,'permanent','📝',true,null),
('card_v41_rare_087','Core Supabase','rare','tech','Carte rare liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',2,'permanent','🔌',true,null),
('card_v41_rare_088','Beta Focus','rare','organisation','Carte rare liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',2,'permanent','✅',true,null),
('card_v41_rare_089','Nexus Focus','rare','organisation','Carte rare liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',2,'permanent','📝',true,null),
('card_v41_rare_090','Soft Loot','rare','gaming','Carte rare liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',2,'permanent','🕹️',true,null),
('card_v41_rare_091','Nexus Sac','rare','life','Carte rare liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',2,'permanent','🎒',true,null),
('card_v41_rare_092','Neo Ordre','rare','organisation','Carte rare liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',2,'permanent','📝',true,null),
('card_v41_rare_093','Spark JavaScript','rare','tech','Carte rare liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',2,'permanent','💻',true,null),
('card_v41_rare_094','Nexus Exercice','rare','study','Carte rare liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',2,'permanent','📖',true,null),
('card_v41_rare_095','Quantum Quête','rare','gaming','Carte rare liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',2,'permanent','⚡',true,null),
('card_v41_rare_096','Alpha Montage','rare','creative','Carte rare liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',2,'permanent','🌈',true,null),
('card_v41_rare_097','Vector Dashboard','rare','organisation','Carte rare liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',2,'permanent','🧩',true,null),
('card_v41_rare_098','Pixel Checklist','rare','organisation','Carte rare liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',2,'permanent','🧭',true,null),
('card_v41_rare_099','Orbit Document','rare','life','Carte rare liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',2,'permanent','💰',true,null),
('card_v41_rare_100','Quantum Code','rare','tech','Carte rare liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',2,'permanent','🔌',true,null),
('card_v41_rare_101','Quantum Routine','rare','organisation','Carte rare liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',2,'permanent','🧩',true,null),
('card_v41_rare_102','Quantum YouTube','rare','creative','Carte rare liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',2,'permanent','🖌️',true,null),
('card_v41_rare_103','Orbit Gacha','rare','gaming','Carte rare liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',2,'permanent','⚡',true,null),
('card_v41_rare_104','Quantum Énergie','rare','life','Carte rare liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',2,'permanent','🏠',true,null),
('card_v41_rare_105','Origin Achat','rare','life','Carte rare liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',2,'permanent','🎧',true,null),
('card_v41_rare_106','Quantum Idée','rare','creative','Carte rare liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',2,'permanent','🖌️',true,null),
('card_v41_rare_107','Quantum Codex','rare','gaming','Carte rare liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',2,'permanent','🎲',true,null),
('card_v41_rare_108','Ultra Organisation','rare','life','Carte rare liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',2,'permanent','🎧',true,null),
('card_v41_rare_109','Nova Dashboard','rare','organisation','Carte rare liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',2,'permanent','⚙️',true,null),
('card_v41_rare_110','Spark Révision','rare','study','Carte rare liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',2,'permanent','📚',true,null),
('card_v41_rare_111','Pixel Sac','rare','life','Carte rare liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',2,'permanent','📄',true,null),
('card_v41_rare_112','Core Mission','rare','organisation','Carte rare liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',2,'permanent','✅',true,null),
('card_v41_rare_113','Mini Semaine','rare','organisation','Carte rare liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',2,'permanent','🧩',true,null),
('card_v41_rare_114','Spark HTML','rare','tech','Carte rare liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',2,'permanent','🐙',true,null),
('card_v41_rare_115','Cyber Semaine','rare','organisation','Carte rare liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',2,'permanent','🧩',true,null),
('card_v41_rare_116','Vector Idée','rare','creative','Carte rare liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',2,'permanent','🖌️',true,null),
('card_v41_rare_117','Cyber Quête','rare','gaming','Carte rare liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',2,'permanent','🎲',true,null),
('card_v41_rare_118','Core XP','rare','gaming','Carte rare liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',2,'permanent','🕹️',true,null),
('card_v41_rare_119','Orbit Idée','rare','creative','Carte rare liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',2,'permanent','🖌️',true,null),
('card_v41_rare_120','Cyber Codex','rare','gaming','Carte rare liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',2,'permanent','🎟️',true,null),
('card_v41_rare_121','Nova Niveau','rare','gaming','Carte rare liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',2,'permanent','🎟️',true,null),
('card_v41_rare_122','Neo Montage','rare','creative','Carte rare liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',2,'permanent','📸',true,null),
('card_v41_rare_123','Pulse Quête','rare','gaming','Carte rare liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',2,'permanent','🕹️',true,null),
('card_v41_rare_124','Pixel Inventaire','rare','life','Carte rare liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',2,'permanent','📇',true,null),
('card_v41_rare_125','Soft Loot','rare','gaming','Carte rare liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',2,'permanent','🎟️',true,null),
('card_v41_rare_126','Beta Supabase','rare','tech','Carte rare liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',2,'permanent','💻',true,null),
('card_v41_rare_127','Nexus Sujet','rare','study','Carte rare liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',2,'permanent','📖',true,null),
('card_v41_rare_128','Soft Méthode','rare','study','Carte rare liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',2,'permanent','✏️',true,null),
('card_v41_rare_129','Echo Méthode','rare','study','Carte rare liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',2,'permanent','📚',true,null),
('card_v41_rare_130','Vector Ordre','rare','organisation','Carte rare liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',2,'permanent','🗓️',true,null),
('card_v41_rare_131','Pulse YouTube','rare','creative','Carte rare liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',2,'permanent','🖌️',true,null),
('card_v41_rare_132','Beta Studio','rare','creative','Carte rare liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',2,'permanent','🎬',true,null),
('card_v41_rare_133','Beta JavaScript','rare','tech','Carte rare liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',2,'permanent','🐙',true,null),
('card_v41_rare_134','Origin Niveau','rare','gaming','Carte rare liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',2,'permanent','⚡',true,null),
('card_v41_rare_135','Nexus Code','rare','tech','Carte rare liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',2,'permanent','💻',true,null),
('card_v41_epic_136','Soft Organisation','epic','life','Carte epic liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',5,'permanent','📄',true,null),
('card_v41_epic_137','Soft Semaine','epic','organisation','Carte epic liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',5,'permanent','📌',true,null),
('card_v41_epic_138','Pulse Quête','epic','gaming','Carte epic liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',5,'permanent','⭐',true,null),
('card_v41_epic_139','Core JavaScript','epic','tech','Carte epic liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',5,'permanent','🖥️',true,null),
('card_v41_epic_140','Spark JavaScript','epic','tech','Carte epic liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',5,'permanent','⌨️',true,null),
('card_v41_epic_141','Hyper Ticket','epic','gaming','Carte epic liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',5,'permanent','🕹️',true,null),
('card_v41_epic_142','Orbit Bug','epic','tech','Carte epic liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',5,'permanent','⌨️',true,null),
('card_v41_epic_143','Spark Niveau','epic','gaming','Carte epic liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',5,'permanent','🎟️',true,null),
('card_v41_epic_144','Neo Cours','epic','study','Carte epic liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',5,'permanent','🧪',true,null),
('card_v41_epic_145','Soft Annale','epic','study','Carte epic liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',5,'permanent','🧠',true,null),
('card_v41_epic_146','Hyper Interface','epic','tech','Carte epic liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',5,'permanent','🛠️',true,null),
('card_v41_epic_147','Mini Gacha','epic','gaming','Carte epic liée à gaming. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à gaming.','gaming',5,'permanent','🎟️',true,null),
('card_v41_epic_148','Neo Focus','epic','organisation','Carte epic liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',5,'permanent','🧩',true,null),
('card_v41_epic_149','Neo GitHub','epic','tech','Carte epic liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',5,'permanent','⌨️',true,null),
('card_v41_epic_150','Mini Énergie','epic','life','Carte epic liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',5,'permanent','📇',true,null),
('card_v41_epic_151','Nova Semaine','epic','organisation','Carte epic liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',5,'permanent','📌',true,null),
('card_v41_epic_152','Neo Budget','epic','life','Carte epic liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',5,'permanent','🎧',true,null),
('card_v41_epic_153','Pulse HTML','epic','tech','Carte epic liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',5,'permanent','🛠️',true,null),
('card_v41_epic_154','Vector Pixel','epic','creative','Carte epic liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',5,'permanent','🟦',true,null),
('card_v41_epic_155','Alpha Miniature','epic','creative','Carte epic liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',5,'permanent','🌈',true,null),
('card_v41_epic_156','Prime Dashboard','epic','organisation','Carte epic liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',5,'permanent','🗓️',true,null),
('card_v41_epic_157','Core Montage','epic','creative','Carte epic liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',5,'permanent','📸',true,null),
('card_v41_epic_158','Spark Focus','epic','organisation','Carte epic liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',5,'permanent','🗓️',true,null),
('card_v41_epic_159','Echo Événement','epic','life','Carte epic liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',5,'permanent','🛒',true,null),
('card_v41_epic_160','Beta Ordre','epic','organisation','Carte epic liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',5,'permanent','📌',true,null),
('card_v41_epic_161','Beta Couleur','epic','creative','Carte epic liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',5,'permanent','🖌️',true,null),
('card_v41_epic_162','Soft Terminal','epic','tech','Carte epic liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',5,'permanent','🌐',true,null),
('card_v41_epic_163','Alpha Document','epic','life','Carte epic liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',5,'permanent','🛒',true,null),
('card_v41_epic_164','Soft Montage','epic','creative','Carte epic liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',5,'permanent','🟦',true,null),
('card_v41_epic_165','Mini Sac','epic','life','Carte epic liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',5,'permanent','📄',true,null),
('card_v41_epic_166','Alpha Checklist','epic','organisation','Carte epic liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',5,'permanent','🧩',true,null),
('card_v41_epic_167','Mini Énergie','epic','life','Carte epic liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',5,'permanent','📇',true,null),
('card_v41_epic_168','Ultra Inventaire','epic','life','Carte epic liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',5,'permanent','📇',true,null),
('card_v41_epic_169','Orbit Miniature','epic','creative','Carte epic liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',5,'permanent','📸',true,null),
('card_v41_epic_170','Neo Révision','epic','study','Carte epic liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',5,'permanent','📖',true,null),
('card_v41_legendary_171','Reset Keeper','legendary','season','Carte legendary liée à season. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à season.','global',10,'spring','🔥',true,null),
('card_v41_legendary_172','Winter Keeper','legendary','season','Carte legendary liée à season. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à season.','global',10,'summer','🌱',true,null),
('card_v41_legendary_173','Build Pilot','legendary','season','Carte legendary liée à season. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à season.','global',10,'focus_mode','🔄',true,null),
('card_v41_legendary_174','Summer Signal','legendary','season','Carte legendary liée à season. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à season.','global',10,'focus_mode','🌱',true,null),
('card_v41_legendary_175','Summer Portal','legendary','season','Carte legendary liée à season. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à season.','global',10,'new_start','🍂',true,null),
('card_v41_legendary_176','Deep Keeper','legendary','season','Carte legendary liée à season. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à season.','global',10,'autumn','🍂',true,null),
('card_v41_legendary_177','Winter Pilot','legendary','season','Carte legendary liée à season. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à season.','global',10,'winter','🌙',true,null),
('card_v41_legendary_178','Summer Flow','legendary','season','Carte legendary liée à season. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à season.','global',10,'build_season','🌸',true,null),
('card_v41_legendary_179','Focus Portal','legendary','season','Carte legendary liée à season. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à season.','global',10,'spring','🔥',true,null),
('card_v41_legendary_180','Summer Architect','legendary','season','Carte legendary liée à season. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à season.','global',10,'new_start','🔥',true,null),
('card_v41_legendary_181','Cyber Interface','legendary','tech','Carte legendary liée à tech. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à tech.','tech',10,'permanent','🛠️',true,null),
('card_v41_legendary_182','Pulse Idée','legendary','creative','Carte legendary liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',10,'permanent','🖌️',true,null),
('card_v41_legendary_183','Origin Idée','legendary','creative','Carte legendary liée à creative. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à creative.','creative',10,'permanent','🎨',true,null),
('card_v41_legendary_184','Orbit Document','legendary','life','Carte legendary liée à life. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à life.','life',10,'permanent','📄',true,null),
('card_v41_legendary_185','Hyper Priorité','legendary','organisation','Carte legendary liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',10,'permanent','✅',true,null),
('card_v41_legendary_186','Hyper Méthode','legendary','study','Carte legendary liée à study. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à study.','study',10,'permanent','🧮',true,null),
('card_v41_legendary_187','Soft Semaine','legendary','organisation','Carte legendary liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',10,'permanent','✅',true,null),
('card_v41_legendary_188','Prime Routine','legendary','organisation','Carte legendary liée à organisation. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à organisation.','organisation',10,'permanent','🎯',true,null),
('card_v41_secret_189','Glitch Protocol','secret','secret','Carte secret liée à secret. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à secret.','global',12,'permanent','⌨️',true,null),
('card_v41_secret_190','Shadow Core','secret','secret','Carte secret liée à secret. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à secret.','global',12,'permanent','👻',true,null),
('card_v41_secret_191','Midnight Signal','secret','secret','Carte secret liée à secret. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à secret.','global',12,'permanent','🌌',true,null),
('card_v41_secret_192','Hidden Engine','secret','secret','Carte secret liée à secret. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à secret.','global',12,'permanent','👻',true,null),
('card_v41_secret_193','Ghost Path','secret','secret','Carte secret liée à secret. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à secret.','global',12,'permanent','🕳️',true,null),
('card_v41_secret_194','404 Module','secret','secret','Carte secret liée à secret. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à secret.','global',12,'permanent','🌌',true,null),
('card_v41_secret_195','Void Matrix','secret','secret','Carte secret liée à secret. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à secret.','global',12,'permanent','🌌',true,null),
('card_v41_secret_196','Cipher Runner','secret','secret','Carte secret liée à secret. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à secret.','global',12,'permanent','👻',true,null),
('card_v41_secret_197','Eclipse Keeper','secret','secret','Carte secret liée à secret. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à secret.','global',12,'permanent','🗝️',true,null),
('card_v41_celestial_198','Cœur Céleste','celestial','celestial','Carte celestial liée à celestial. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à celestial.','global',15,'permanent','💠',true,'second_title_slot'),
('card_v41_celestial_199','Admin Originel','celestial','celestial','Carte celestial liée à celestial. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à celestial.','global',15,'permanent','💠',true,null),
('card_v41_celestial_200','Compilateur Divin','celestial','celestial','Carte celestial liée à celestial. Elle enrichit la collection Optimize et la progression ludique.','Déblocable via gacha, codes, progression ou événements liés à celestial.','global',15,'permanent','👑',true,null)
on conflict (id) do update set
  name = excluded.name,
  rarity = excluded.rarity,
  category = excluded.category,
  description = excluded.description,
  condition_hint = excluded.condition_hint,
  boost_type = excluded.boost_type,
  boost_value = excluded.boost_value,
  season = excluded.season,
  icon = excluded.icon,
  active = excluded.active,
  unlocks = excluded.unlocks,
  updated_at = now();

insert into public.companions
(id, name, rarity, family, description, phrase, boost_type, boost_value, season, icon, active, unlocks, price, gacha_only, value, boost_scope, starter)
values
('pet_robot','Robot Optimize','common','robot','Compagnon de base, fiable et neutre.','Je suis prêt à t’aider à organiser le chaos.','global',0,'permanent','🤖',true,null,0,false,'robot','equipped',true),
('pet_v41_common_002','Arcade Orbe','common','animal','Compagnon common de famille animal, pensé pour le QG Optimize.','Objectif verrouillé.','global',0,'permanent','🐇',true,null,9,false,'pet_v41_common_002','equipped',false),
('pet_v41_common_003','Blue Cube','common','robot','Compagnon common de famille robot, pensé pour le QG Optimize.','XP détectée.','global',0,'permanent','🔩',true,null,10,false,'pet_v41_common_003','equipped',false),
('pet_v41_common_004','Quantum Golem','common','drone','Compagnon common de famille drone, pensé pour le QG Optimize.','XP détectée.','drone',0,'permanent','📡',true,null,11,false,'pet_v41_common_004','equipped',false),
('pet_v41_common_005','Cyber Vaisseau','common','glitch','Compagnon common de famille glitch, pensé pour le QG Optimize.','XP détectée.','glitch',0,'permanent','👻',true,null,12,false,'pet_v41_common_005','equipped',false),
('pet_v41_common_006','Pixel IA','common','ai','Compagnon common de famille ai, pensé pour le QG Optimize.','On garde le cap.','global',0,'permanent','🔮',true,null,13,false,'pet_v41_common_006','equipped',false),
('pet_v41_common_007','Tiny Orbe','common','animal','Compagnon common de famille animal, pensé pour le QG Optimize.','Progression stable.','global',0,'permanent','🐺',true,null,14,false,'pet_v41_common_007','equipped',false),
('pet_v41_common_008','Night Mage','common','study','Compagnon common de famille study, pensé pour le QG Optimize.','Je surveille le cockpit.','study',0,'permanent','📘',true,null,15,false,'pet_v41_common_008','equipped',false),
('pet_v41_common_009','Soft Mage','common','pixel','Compagnon common de famille pixel, pensé pour le QG Optimize.','Niveau suivant en vue.','pixel',0,'permanent','🟩',true,null,16,false,'pet_v41_common_009','equipped',false),
('pet_v41_common_010','Pixel Loup','common','dragon','Compagnon common de famille dragon, pensé pour le QG Optimize.','Objectif verrouillé.','dragon',0,'permanent','🐲',true,null,17,false,'pet_v41_common_010','equipped',false),
('pet_v41_common_011','Pixel Mage','common','glitch','Compagnon common de famille glitch, pensé pour le QG Optimize.','Je surveille le cockpit.','glitch',0,'permanent','👻',true,null,8,false,'pet_v41_common_011','equipped',false),
('pet_v41_common_012','Soft IA','common','space','Compagnon common de famille space, pensé pour le QG Optimize.','Progression stable.','global',0,'permanent','🌠',true,null,9,false,'pet_v41_common_012','equipped',false),
('pet_v41_common_013','Arcade Dragon','common','study','Compagnon common de famille study, pensé pour le QG Optimize.','Niveau suivant en vue.','study',0,'permanent','📘',true,null,10,false,'pet_v41_common_013','equipped',false),
('pet_v41_common_014','Soft Terminal','common','season','Compagnon common de famille season, pensé pour le QG Optimize.','Progression stable.','global',0,'summer','🍂',true,null,11,false,'pet_v41_common_014','equipped',false),
('pet_v41_common_015','Spark Gardien','common','ai','Compagnon common de famille ai, pensé pour le QG Optimize.','Je surveille le cockpit.','global',0,'permanent','🔮',true,null,12,false,'pet_v41_common_015','equipped',false),
('pet_v41_common_016','Quantum Vaisseau','common','holo','Compagnon common de famille holo, pensé pour le QG Optimize.','Progression stable.','global',0,'permanent','💠',true,null,13,false,'pet_v41_common_016','equipped',false),
('pet_v41_common_017','Spark Ninja','common','glitch','Compagnon common de famille glitch, pensé pour le QG Optimize.','Progression stable.','glitch',0,'permanent','🐈‍⬛',true,null,14,false,'pet_v41_common_017','equipped',false),
('pet_v41_common_018','Tiny Oracle','common','season','Compagnon common de famille season, pensé pour le QG Optimize.','Objectif verrouillé.','global',0,'summer','🌱',true,null,15,false,'pet_v41_common_018','equipped',false),
('pet_v41_common_019','Golden Mage','common','dragon','Compagnon common de famille dragon, pensé pour le QG Optimize.','Je surveille le cockpit.','dragon',0,'permanent','🐲',true,null,16,false,'pet_v41_common_019','equipped',false),
('pet_v41_common_020','Cyber Terminal','common','glitch','Compagnon common de famille glitch, pensé pour le QG Optimize.','XP détectée.','glitch',0,'permanent','👻',true,null,17,false,'pet_v41_common_020','equipped',false),
('pet_v41_common_021','Spark Chat','common','holo','Compagnon common de famille holo, pensé pour le QG Optimize.','XP détectée.','global',0,'permanent','🟧',true,null,8,false,'pet_v41_common_021','equipped',false),
('pet_v41_common_022','Night Bot','common','robot','Compagnon common de famille robot, pensé pour le QG Optimize.','Mission prête.','global',0,'permanent','⚙️',true,null,9,false,'pet_v41_common_022','equipped',false),
('pet_v41_common_023','Orbit IA','common','animal','Compagnon common de famille animal, pensé pour le QG Optimize.','Progression stable.','global',0,'permanent','🦉',true,null,10,false,'pet_v41_common_023','equipped',false),
('pet_v41_common_024','Glitch Chat','common','tech','Compagnon common de famille tech, pensé pour le QG Optimize.','Je surveille le cockpit.','tech',0,'permanent','⌨️',true,null,11,false,'pet_v41_common_024','equipped',false),
('pet_v41_common_025','Neo Renard','common','animal','Compagnon common de famille animal, pensé pour le QG Optimize.','Je surveille le cockpit.','global',0,'permanent','🦉',true,null,12,false,'pet_v41_common_025','equipped',false),
('pet_v41_common_026','Spark Bot','common','space','Compagnon common de famille space, pensé pour le QG Optimize.','XP détectée.','global',0,'permanent','🌠',true,null,13,false,'pet_v41_common_026','equipped',false),
('pet_v41_common_027','Holo Renard','common','holo','Compagnon common de famille holo, pensé pour le QG Optimize.','Progression stable.','global',0,'permanent','💠',true,null,14,false,'pet_v41_common_027','equipped',false),
('pet_v41_common_028','Quantum Renard','common','mage','Compagnon common de famille mage, pensé pour le QG Optimize.','On garde le cap.','mage',0,'permanent','🧙',true,null,15,false,'pet_v41_common_028','equipped',false),
('pet_v41_common_029','Arcade Drone','common','mage','Compagnon common de famille mage, pensé pour le QG Optimize.','Objectif verrouillé.','mage',0,'permanent','🧙',true,null,16,false,'pet_v41_common_029','equipped',false),
('pet_v41_common_030','Shadow Orbe','common','tech','Compagnon common de famille tech, pensé pour le QG Optimize.','Je surveille le cockpit.','tech',0,'permanent','⌨️',true,null,17,false,'pet_v41_common_030','equipped',false),
('pet_v41_common_031','Spark Vaisseau','common','mage','Compagnon common de famille mage, pensé pour le QG Optimize.','Progression stable.','mage',0,'permanent','🪄',true,null,8,false,'pet_v41_common_031','equipped',false),
('pet_v41_common_032','Blue Sprite','common','glitch','Compagnon common de famille glitch, pensé pour le QG Optimize.','Objectif verrouillé.','glitch',0,'permanent','🐈‍⬛',true,null,9,false,'pet_v41_common_032','equipped',false),
('pet_v41_common_033','Blue Tigre','common','tech','Compagnon common de famille tech, pensé pour le QG Optimize.','Je surveille le cockpit.','tech',0,'permanent','⌨️',true,null,10,false,'pet_v41_common_033','equipped',false),
('pet_v41_common_034','Arcade Mage','common','mage','Compagnon common de famille mage, pensé pour le QG Optimize.','Niveau suivant en vue.','mage',0,'permanent','🧙',true,null,11,false,'pet_v41_common_034','equipped',false),
('pet_v41_common_035','Holo Orbe','common','drone','Compagnon common de famille drone, pensé pour le QG Optimize.','Objectif verrouillé.','drone',0,'permanent','🚁',true,null,12,false,'pet_v41_common_035','equipped',false),
('pet_v41_common_036','Nova Sprite','common','tech','Compagnon common de famille tech, pensé pour le QG Optimize.','Je surveille le cockpit.','tech',0,'permanent','💻',true,null,13,false,'pet_v41_common_036','equipped',false),
('pet_v41_common_037','Holo Tigre','common','guardian','Compagnon common de famille guardian, pensé pour le QG Optimize.','XP détectée.','guardian',0,'permanent','🛡️',true,null,14,false,'pet_v41_common_037','equipped',false),
('pet_v41_common_038','Soft Drone','common','animal','Compagnon common de famille animal, pensé pour le QG Optimize.','Niveau suivant en vue.','global',0,'permanent','🐯',true,null,15,false,'pet_v41_common_038','equipped',false),
('pet_v41_common_039','Holo Cube','common','robot','Compagnon common de famille robot, pensé pour le QG Optimize.','Mission prête.','global',0,'permanent','🤖',true,null,16,false,'pet_v41_common_039','equipped',false),
('pet_v41_common_040','Golden Chat','common','dragon','Compagnon common de famille dragon, pensé pour le QG Optimize.','Objectif verrouillé.','dragon',0,'permanent','🐉',true,null,17,false,'pet_v41_common_040','equipped',false),
('pet_v41_common_041','Orbit Vaisseau','common','arcade','Compagnon common de famille arcade, pensé pour le QG Optimize.','Je surveille le cockpit.','global',0,'permanent','🕹️',true,null,8,false,'pet_v41_common_041','equipped',false),
('pet_v41_common_042','Arcade Cube','common','guardian','Compagnon common de famille guardian, pensé pour le QG Optimize.','On garde le cap.','guardian',0,'permanent','🗿',true,null,9,false,'pet_v41_common_042','equipped',false),
('pet_v41_common_043','Cyber Slime','common','pixel','Compagnon common de famille pixel, pensé pour le QG Optimize.','Mission prête.','pixel',0,'permanent','🟦',true,null,10,false,'pet_v41_common_043','equipped',false),
('pet_v41_common_044','Arcade Ninja','common','pixel','Compagnon common de famille pixel, pensé pour le QG Optimize.','Mission prête.','pixel',0,'permanent','🟦',true,null,11,false,'pet_v41_common_044','equipped',false),
('pet_v41_common_045','Pixel Golem','common','ai','Compagnon common de famille ai, pensé pour le QG Optimize.','Progression stable.','global',0,'permanent','🔮',true,null,12,false,'pet_v41_common_045','equipped',false),
('pet_v41_rare_046','Tiny Ninja','rare','robot','Compagnon rare de famille robot, pensé pour le QG Optimize.','On garde le cap.','global',2,'permanent','⚙️',true,null,25,false,'pet_v41_rare_046','equipped',false),
('pet_v41_rare_047','Nova Vaisseau','rare','mage','Compagnon rare de famille mage, pensé pour le QG Optimize.','XP détectée.','mage',2,'permanent','🧙',true,null,26,false,'pet_v41_rare_047','equipped',false),
('pet_v41_rare_048','Quantum Oracle','rare','ai','Compagnon rare de famille ai, pensé pour le QG Optimize.','On garde le cap.','global',2,'permanent','🧊',true,null,27,false,'pet_v41_rare_048','equipped',false),
('pet_v41_rare_049','Pixel IA','rare','guardian','Compagnon rare de famille guardian, pensé pour le QG Optimize.','Progression stable.','guardian',2,'permanent','🗿',true,null,28,false,'pet_v41_rare_049','equipped',false),
('pet_v41_rare_050','Soft Ninja','rare','study','Compagnon rare de famille study, pensé pour le QG Optimize.','On garde le cap.','study',2,'permanent','✏️',true,null,29,false,'pet_v41_rare_050','equipped',false),
('pet_v41_rare_051','Prime Ninja','rare','dragon','Compagnon rare de famille dragon, pensé pour le QG Optimize.','Je surveille le cockpit.','dragon',2,'permanent','🐉',true,null,30,false,'pet_v41_rare_051','equipped',false),
('pet_v41_rare_052','Cyber Slime','rare','tech','Compagnon rare de famille tech, pensé pour le QG Optimize.','XP détectée.','tech',2,'permanent','⌨️',true,null,31,false,'pet_v41_rare_052','equipped',false),
('pet_v41_rare_053','Tiny Golem','rare','study','Compagnon rare de famille study, pensé pour le QG Optimize.','Niveau suivant en vue.','study',2,'permanent','📚',true,null,32,false,'pet_v41_rare_053','equipped',false),
('pet_v41_rare_054','Tiny Vaisseau','rare','study','Compagnon rare de famille study, pensé pour le QG Optimize.','Niveau suivant en vue.','study',2,'permanent','✏️',true,null,33,false,'pet_v41_rare_054','equipped',false),
('pet_v41_rare_055','Shadow Hibou','rare','pixel','Compagnon rare de famille pixel, pensé pour le QG Optimize.','Mission prête.','pixel',2,'permanent','👾',true,null,34,false,'pet_v41_rare_055','equipped',false),
('pet_v41_rare_056','Blue Sprite','rare','space','Compagnon rare de famille space, pensé pour le QG Optimize.','Objectif verrouillé.','global',2,'permanent','🚀',true,null,35,false,'pet_v41_rare_056','equipped',false),
('pet_v41_rare_057','Glitch IA','rare','study','Compagnon rare de famille study, pensé pour le QG Optimize.','On garde le cap.','study',2,'permanent','📚',true,null,36,false,'pet_v41_rare_057','equipped',false),
('pet_v41_rare_058','Echo Gardien','rare','ai','Compagnon rare de famille ai, pensé pour le QG Optimize.','Objectif verrouillé.','global',2,'permanent','🧠',true,null,37,false,'pet_v41_rare_058','equipped',false),
('pet_v41_rare_059','Holo Terminal','rare','robot','Compagnon rare de famille robot, pensé pour le QG Optimize.','Mission prête.','global',2,'permanent','🤖',true,null,38,false,'pet_v41_rare_059','equipped',false),
('pet_v41_rare_060','Tiny Bot','rare','space','Compagnon rare de famille space, pensé pour le QG Optimize.','On garde le cap.','global',2,'permanent','🚀',true,null,39,false,'pet_v41_rare_060','equipped',false),
('pet_v41_rare_061','Tiny Chat','rare','study','Compagnon rare de famille study, pensé pour le QG Optimize.','XP détectée.','study',2,'permanent','📚',true,null,40,false,'pet_v41_rare_061','equipped',false),
('pet_v41_rare_062','Neo Terminal','rare','robot','Compagnon rare de famille robot, pensé pour le QG Optimize.','XP détectée.','global',2,'permanent','⚙️',true,null,41,false,'pet_v41_rare_062','equipped',false),
('pet_v41_rare_063','Night Orbe','rare','space','Compagnon rare de famille space, pensé pour le QG Optimize.','On garde le cap.','global',2,'permanent','🌠',true,null,42,false,'pet_v41_rare_063','equipped',false),
('pet_v41_rare_064','Solar Oracle','rare','robot','Compagnon rare de famille robot, pensé pour le QG Optimize.','XP détectée.','global',2,'permanent','⚙️',true,null,43,false,'pet_v41_rare_064','equipped',false),
('pet_v41_rare_065','Mini Renard','rare','animal','Compagnon rare de famille animal, pensé pour le QG Optimize.','Progression stable.','global',2,'permanent','🦊',true,null,44,false,'pet_v41_rare_065','equipped',false),
('pet_v41_rare_066','Orbit Renard','rare','glitch','Compagnon rare de famille glitch, pensé pour le QG Optimize.','XP détectée.','glitch',2,'permanent','👻',true,null,45,false,'pet_v41_rare_066','equipped',false),
('pet_v41_rare_067','Soft Vaisseau','rare','study','Compagnon rare de famille study, pensé pour le QG Optimize.','XP détectée.','study',2,'permanent','✏️',true,null,46,false,'pet_v41_rare_067','equipped',false),
('pet_v41_rare_068','Blue Hibou','rare','animal','Compagnon rare de famille animal, pensé pour le QG Optimize.','On garde le cap.','global',2,'permanent','🦉',true,null,47,false,'pet_v41_rare_068','equipped',false),
('pet_v41_rare_069','Night IA','rare','dragon','Compagnon rare de famille dragon, pensé pour le QG Optimize.','Mission prête.','dragon',2,'permanent','🐉',true,null,48,false,'pet_v41_rare_069','equipped',false),
('pet_v41_rare_070','Arcade Cube','rare','tech','Compagnon rare de famille tech, pensé pour le QG Optimize.','Niveau suivant en vue.','tech',2,'permanent','⌨️',true,null,49,false,'pet_v41_rare_070','equipped',false),
('pet_v41_epic_071','Neo Chat','epic','pixel','Compagnon epic de famille pixel, pensé pour le QG Optimize.','On garde le cap.','pixel',5,'permanent','🟦',true,null,0,true,'pet_v41_epic_071','equipped',false),
('pet_v41_epic_072','Neo Ninja','epic','pixel','Compagnon epic de famille pixel, pensé pour le QG Optimize.','XP détectée.','pixel',5,'permanent','👾',true,null,0,true,'pet_v41_epic_072','equipped',false),
('pet_v41_epic_073','Solar Mage','epic','holo','Compagnon epic de famille holo, pensé pour le QG Optimize.','XP détectée.','global',5,'permanent','🔷',true,null,0,true,'pet_v41_epic_073','equipped',false),
('pet_v41_epic_074','Blue Cube','epic','tech','Compagnon epic de famille tech, pensé pour le QG Optimize.','Niveau suivant en vue.','tech',5,'permanent','💻',true,null,0,true,'pet_v41_epic_074','equipped',false),
('pet_v41_epic_075','Golden Oracle','epic','study','Compagnon epic de famille study, pensé pour le QG Optimize.','XP détectée.','study',5,'permanent','✏️',true,null,0,true,'pet_v41_epic_075','equipped',false),
('pet_v41_epic_076','Neo Bot','epic','holo','Compagnon epic de famille holo, pensé pour le QG Optimize.','Progression stable.','global',5,'permanent','🔷',true,null,0,true,'pet_v41_epic_076','equipped',false),
('pet_v41_epic_077','Pixel Vaisseau','epic','drone','Compagnon epic de famille drone, pensé pour le QG Optimize.','Niveau suivant en vue.','drone',5,'permanent','🚁',true,null,0,true,'pet_v41_epic_077','equipped',false),
('pet_v41_epic_078','Nova Vaisseau','epic','holo','Compagnon epic de famille holo, pensé pour le QG Optimize.','Niveau suivant en vue.','global',5,'permanent','🟧',true,null,0,true,'pet_v41_epic_078','equipped',false),
('pet_v41_epic_079','Echo Terminal','epic','mage','Compagnon epic de famille mage, pensé pour le QG Optimize.','On garde le cap.','mage',5,'permanent','🪄',true,null,0,true,'pet_v41_epic_079','equipped',false),
('pet_v41_epic_080','Soft Renard','epic','animal','Compagnon epic de famille animal, pensé pour le QG Optimize.','Niveau suivant en vue.','global',5,'permanent','🦉',true,null,0,true,'pet_v41_epic_080','equipped',false),
('pet_v41_epic_081','Holo Bot','epic','glitch','Compagnon epic de famille glitch, pensé pour le QG Optimize.','Je surveille le cockpit.','glitch',5,'permanent','🐈‍⬛',true,null,0,true,'pet_v41_epic_081','equipped',false),
('pet_v41_epic_082','Holo Terminal','epic','tech','Compagnon epic de famille tech, pensé pour le QG Optimize.','XP détectée.','tech',5,'permanent','⌨️',true,null,0,true,'pet_v41_epic_082','equipped',false),
('pet_v41_epic_083','Cyber Vaisseau','epic','space','Compagnon epic de famille space, pensé pour le QG Optimize.','Niveau suivant en vue.','global',5,'permanent','🌌',true,null,0,true,'pet_v41_epic_083','equipped',false),
('pet_v41_epic_084','Tiny Orbe','epic','robot','Compagnon epic de famille robot, pensé pour le QG Optimize.','Mission prête.','global',5,'permanent','⚙️',true,null,0,true,'pet_v41_epic_084','equipped',false),
('pet_v41_epic_085','Pixel Vaisseau','epic','glitch','Compagnon epic de famille glitch, pensé pour le QG Optimize.','XP détectée.','glitch',5,'permanent','🐈‍⬛',true,null,0,true,'pet_v41_epic_085','equipped',false),
('pet_v41_epic_086','Solar Loup','epic','guardian','Compagnon epic de famille guardian, pensé pour le QG Optimize.','Progression stable.','guardian',5,'permanent','🗿',true,null,0,true,'pet_v41_epic_086','equipped',false),
('pet_v41_epic_087','Glitch Sprite','epic','guardian','Compagnon epic de famille guardian, pensé pour le QG Optimize.','Niveau suivant en vue.','guardian',5,'permanent','🗿',true,null,0,true,'pet_v41_epic_087','equipped',false),
('pet_v41_epic_088','Orbit Bot','epic','arcade','Compagnon epic de famille arcade, pensé pour le QG Optimize.','XP détectée.','global',5,'permanent','🕹️',true,null,0,true,'pet_v41_epic_088','equipped',false),
('pet_v41_legendary_089','Glitch Hibou','legendary','season','Compagnon legendary de famille season, pensé pour le QG Optimize.','Objectif verrouillé.','global',10,'spring','☀️',true,null,0,true,'pet_v41_legendary_089','equipped',false),
('pet_v41_legendary_090','Soft Oracle','legendary','season','Compagnon legendary de famille season, pensé pour le QG Optimize.','Objectif verrouillé.','global',10,'summer','🌱',true,null,0,true,'pet_v41_legendary_090','equipped',false),
('pet_v41_legendary_091','Mini Chat','legendary','arcade','Compagnon legendary de famille arcade, pensé pour le QG Optimize.','Je surveille le cockpit.','global',10,'permanent','🕹️',true,null,0,true,'pet_v41_legendary_091','equipped',false),
('pet_v41_legendary_092','Glitch Cube','legendary','season','Compagnon legendary de famille season, pensé pour le QG Optimize.','Objectif verrouillé.','global',10,'winter','🌱',true,null,0,true,'pet_v41_legendary_092','equipped',false),
('pet_v41_legendary_093','Blue Renard','legendary','guardian','Compagnon legendary de famille guardian, pensé pour le QG Optimize.','On garde le cap.','guardian',10,'permanent','🗿',true,null,0,true,'pet_v41_legendary_093','equipped',false),
('pet_v41_legendary_094','Nova Drone','legendary','holo','Compagnon legendary de famille holo, pensé pour le QG Optimize.','Mission prête.','global',10,'permanent','🔷',true,null,0,true,'pet_v41_legendary_094','equipped',false),
('pet_v41_legendary_095','Nova Gardien','legendary','season','Compagnon legendary de famille season, pensé pour le QG Optimize.','Progression stable.','global',10,'spring','🌱',true,null,0,true,'pet_v41_legendary_095','equipped',false),
('pet_v41_legendary_096','Arcade Bot','legendary','study','Compagnon legendary de famille study, pensé pour le QG Optimize.','Niveau suivant en vue.','study',10,'permanent','📚',true,null,0,true,'pet_v41_legendary_096','equipped',false),
('pet_v41_secret_097','Mini Slime','secret','glitch','Compagnon secret de famille glitch, pensé pour le QG Optimize.','Progression stable.','glitch',12,'permanent','🐈‍⬛',true,null,0,true,'pet_v41_secret_097','permanent',false),
('pet_v41_secret_098','Holo Loup','secret','glitch','Compagnon secret de famille glitch, pensé pour le QG Optimize.','Mission prête.','glitch',12,'permanent','👻',true,null,0,true,'pet_v41_secret_098','permanent',false),
('pet_v41_secret_099','Golden Terminal','secret','glitch','Compagnon secret de famille glitch, pensé pour le QG Optimize.','Mission prête.','glitch',12,'permanent','👻',true,null,0,true,'pet_v41_secret_099','permanent',false),
('pet_v41_celestial_100','Spark Sprite','celestial','origin','Compagnon celestial de famille origin, pensé pour le QG Optimize.','XP détectée.','global',15,'permanent','⚡',true,'third_companion_slot',0,true,'pet_v41_celestial_100','permanent',false)
on conflict (id) do update set
  name = excluded.name,
  rarity = excluded.rarity,
  family = excluded.family,
  description = excluded.description,
  phrase = excluded.phrase,
  boost_type = excluded.boost_type,
  boost_value = excluded.boost_value,
  season = excluded.season,
  icon = excluded.icon,
  active = excluded.active,
  unlocks = excluded.unlocks,
  price = excluded.price,
  gacha_only = excluded.gacha_only,
  value = excluded.value,
  boost_scope = excluded.boost_scope,
  starter = excluded.starter,
  updated_at = now();

insert into public.secret_codes
(code, label, message, reward_type, reward_id, tickets, min_level, active, expires_at)
values
('START','Code de départ','Démarrage validé : carte commune +1 ticket.','card','card_first_steps',1,1,true,null),
('KARATE','Esprit combatif','Esprit combatif : +1 ticket.','tickets',null,1,1,true,null),
('PIXEL','Signal pixel','Signal pixel : compagnon rare débloqué.','reward','pet_pixel',1,1,true,null),
('DEBUG','Debug prudent','Débugueur prudent : petit bonus commun.','reward','pet_terminal',1,1,true,null),
('OPTIMIZE','Utilisateur curieux','Utilisateur curieux : titre rare débloqué.','reward','title_planner',1,1,true,null),
('HUB','Portail actif','Carte Hub Starter + 1 ticket.','card','card_site_seed',1,1,true,null),
('STUDIO','Studio créatif','Carte créative rare + 1 ticket.','card','card_youtube_mind',1,1,true,null),
('BUDGET','Budget propre','Carte budget commune + 1 ticket.','card','card_budget_coin',1,1,true,null),
('404','Erreur repérée','Erreur repérée : carte tech rare +1 ticket.','card','card_code_words',1,1,true,null)
on conflict (code) do update set
  label = excluded.label,
  message = excluded.message,
  reward_type = excluded.reward_type,
  reward_id = excluded.reward_id,
  tickets = excluded.tickets,
  min_level = excluded.min_level,
  active = excluded.active,
  expires_at = excluded.expires_at,
  updated_at = now();

alter table public.secret_codes enable row level security;
alter table public.user_secret_codes enable row level security;

drop policy if exists secret_codes_select_active on public.secret_codes;
create policy secret_codes_select_active on public.secret_codes
  for select using (active = true);

drop policy if exists user_secret_codes_select_own on public.user_secret_codes;
drop policy if exists user_secret_codes_insert_own on public.user_secret_codes;
drop policy if exists user_secret_codes_update_own on public.user_secret_codes;
drop policy if exists user_secret_codes_delete_own on public.user_secret_codes;

create policy user_secret_codes_select_own on public.user_secret_codes
  for select using (auth.uid() = user_id);

create policy user_secret_codes_insert_own on public.user_secret_codes
  for insert with check (auth.uid() = user_id);

create policy user_secret_codes_update_own on public.user_secret_codes
  for update using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy user_secret_codes_delete_own on public.user_secret_codes
  for delete using (auth.uid() = user_id);
